services:
  postgres:
    image: postgres:17
    container_name: db-docvault
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123123
      - POSTGRES_DB=db-docvault
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: